Repository boostcamp-2020/Project15-C-Client-Based-Formula-Editor, pull requests merged in 2020-11, with the labels that each got.

#17 #13 수신 선택 드롭다운의 소스 생성
  client/.eslintrc.json
  client/src/lib/constants/latex-header.ts
Labels: ⚒️ feature, 🖼️ frontend

#18 #13- latex data 이스케이프 수정 및 latex 이미지 추가
  client/public/image/12-btn.svg
  client/public/image/13-btn.svg
  client/public/image/14-btn.svg
  client/public/image/15-btn.svg
  client/public/image/16-btn.svg
  client/public/image/17-btn.svg
  client/src/components/Cook/FormulaList/index.tsx
  client/src/lib/constants/latex-header.ts
Labels: 🐞 bugfix, 🖼️ frontend

#20 헤더 스타일 구현
  client/public/content.css
  client/public/root.css
  client/src/components/Cook/FormulaList/index.tsx
  client/src/components/Cook/FormulaList/style.ts
  client/src/components/Materials/Button/index.tsx
  client/src/components/Materials/DropDownItem/index.tsx
  client/src/components/Materials/DropDownItem/style.ts
  client/src/components/Materials/FormulaItem/index.tsx
  client/src/components/Materials/FormulaItem/style.ts
  client/src/components/Set/Header/style.ts
  client/src/lib/constants/latex-header.ts
  client/src/pages/MainPage.tsx
Labels: ✔️ must, 🖼️ frontend

#21 #8 수식 수정 액션 로직 구현
  client/public/content.css
  client/public/root.css
  client/src/App.tsx
  client/src/components/Cook/Main/index.tsx
  client/src/components/Cook/Main/intex.tsx
  client/src/components/Cook/Main/style.ts
  client/src/components/Cook/SaveButtons/index.tsx
  client/src/components/Cook/SaveButtons/style.ts
  client/src/components/Set/Main/Content.tsx
  client/src/components/Set/Main/index.tsx
  client/src/components/Set/Main/style.ts
  client/src/contexts/latex/actions.ts
  client/src/contexts/latex/reducer.ts
  client/src/contexts/latex/types.ts
  client/src/pages/MainPage.tsx
Labels: ⚒️ feature, 🖼️ frontend

#22 #4 - 메인 컨텐츠 레이아웃 구현
  client/src/components/Cook/Main/index.tsx
  client/src/components/Cook/Main/intex.tsx
  client/src/components/Ingredients/DropDownItem/index.tsx
  client/src/components/Ingredients/DropDownItem/style.ts
  client/src/components/Ingredients/Dropdown/index.tsx
  client/src/components/Ingredients/FormulaItem/index.tsx
  client/src/components/Ingredients/FormulaItem/style.ts
  client/src/components/Meal/Contents/index.tsx
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/HeaderButtons/index.tsx
  client/src/components/Meal/InputContents/index.tsx
  client/src/components/Meal/InputContents/style.ts
  client/src/components/Meal/Main/index.tsx
  client/src/components/Meal/Main/style.ts
  client/src/components/Meal/OutputContents/index.tsx
  client/src/components/Meal/OutputContents/style.ts
  client/src/components/Meal/SaveButtons/index.tsx
  client/src/components/Meal/SaveButtons/style.ts
  client/src/components/Meal/Tab/index.tsx
  client/src/components/Set/Header/index.tsx
  client/src/components/Set/Main/index.tsx
  client/src/pages/MainPage.tsx
Labels: ⚒️ feature, 🖼️ frontend

#24 #4 - contents 우측 레이아웃 및 UI 구현
  client/src/components/Meal/Main/index.tsx
  client/src/components/Meal/OutputArea/index.tsx
  client/src/components/Meal/OutputArea/style.ts
  client/src/components/Meal/OutputContents/index.tsx
  client/src/components/Meal/OutputContents/style.ts
  client/src/components/Meal/SaveButtons/index.tsx
  client/src/components/Meal/SaveButtons/style.ts
  client/src/components/Meal/TemplateButtons/index.tsx
  client/src/components/Meal/TemplateButtons/style.ts
Labels: ⚒️ feature, 🖼️ frontend

#25 # 4 - 수식편집기 전체적인 레이아웃 구성 및 CSS 디자인
  client/.eslintrc.json
  client/src/components/Ingredients/ButtonItem/index.tsx
  client/src/components/Ingredients/TextAreaItem/index.tsx
  client/src/components/Ingredients/TextAreaItem/style.ts
  client/src/components/Meal/InputArea/index.tsx
  client/src/components/Meal/InputArea/style.ts
  client/src/components/Meal/InputContents/index.tsx
  client/src/components/Meal/InputContents/style.ts
  client/src/components/Meal/Main/index.tsx
  client/src/components/Meal/Main/style.ts
  client/src/components/Meal/OutputArea/style.ts
  client/src/components/Meal/OutputContents/style.ts
  client/src/components/Meal/SaveButtons/index.tsx
  client/src/components/Meal/SaveButtons/style.ts
  client/src/components/Meal/Tab/index.tsx
  client/src/components/Meal/Tab/style.ts
  client/src/components/Set/Header/style.ts
  client/src/components/Set/Main/style.ts
Labels: ⚒️ feature, 🖼️ frontend

#23 #12 - initLatex Redux Action 추가
  client/src/components/Ingredients/FormulaItem/index.tsx
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Set/Main/Content.tsx
  client/src/contexts/latex/actions.ts
  client/src/contexts/latex/reducer.ts
  client/src/contexts/latex/types.ts
Labels: ⚒️ feature, ✔️could, 🖼️ frontend

#27 #26 - 탭 관련 리덕스 타입, 액션, 리듀서 생성
  client/package-lock.json
  client/package.json
  client/src/components/Ingredients/FormulaItem/index.tsx
  client/src/components/Meal/OutputContents/index.tsx
  client/src/components/Meal/Tab/MenuItem.tsx
  client/src/components/Meal/Tab/index.tsx
  client/src/components/Set/Main/Content.tsx
  client/src/contexts/latex/actions.ts
  client/src/contexts/latex/reducer.ts
  client/src/contexts/latex/types.ts
  client/src/index.tsx
  client/src/lib/utils/util.js
  client/src/lib/utils/util.ts
Labels: ✔️ must, 🖼️ frontend, 🧥 refactor

#30 #8 - Main Contents action 구현 및 탭 관련 action 적용 및
  client/package-lock.json
  client/package.json
  client/public/content.css
  client/src/components/Ingredients/TextAreaItem/index.tsx
  client/src/components/Meal/OutputContents/index.tsx
  client/src/components/Meal/OutputContents/style.ts
  client/src/components/Meal/Tab/index.tsx
  client/src/components/Set/Main/Content.tsx
  client/src/components/Set/Main/style.ts
  client/src/contexts/latex/actions.ts
  client/src/contexts/latex/types.ts
  client/src/index.tsx
Labels: ⚒️ feature, ✔️ must, 🖼️ frontend

#31 #26 createAction 함수 리팩토링
  client/src/lib/utils/util.ts
Labels: 🖼️ frontend, 🧥 refactor

#32 #5 - 내용 전체 삭제 버튼 생성
  client/src/components/Meal/TemplateButtons/index.tsx
Labels: ⚒️ feature, 🖼️ frontend

#33 #13 - 전체적인 디자인 및 CSS 수정
  client/public/root.css
  client/src/components/Ingredients/DropDownItem/style.ts
  client/src/components/Ingredients/FormulaItem/style.ts
  client/src/components/Ingredients/TextAreaItem/style.ts
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/OutputContents/style.ts
  client/src/components/Meal/TemplateButtons/style.ts
  client/src/components/Set/Main/Content.tsx
  client/src/components/Set/Main/style.ts
  client/src/index.tsx
  client/src/lib/constants/latex-header.ts
Labels: 🖼️ frontend, 🧥 refactor

#37 #35, #36 - Alias 설정 추가, 여러 가지 Bugfix 수행
  client/src/components/Ingredients/FormulaItem/index.tsx
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/Tab/MenuItem.tsx
  client/src/components/Meal/Tab/index.tsx
  client/src/contexts/latex/reducer.ts
  client/src/lib/constants/constants.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: 🐞 bugfix, 🖼️ frontend, 🧥 refactor

#38 #34, #35, #36 버그 수정
  client/src/components/Ingredients/FormulaItem/index.tsx
  client/src/components/Meal/FormulaList/index.tsx
Labels: 🐞 bugfix, 🖼️ frontend, 🧥 refactor

#39 로직 부분 Custom Hook으로 분리
  client/src/components/Ingredients/DropDownItem/index.tsx
  client/src/components/Ingredients/FormulaItem/index.tsx
  client/src/components/Ingredients/FormulaItem/useFormulaItem.ts
  client/src/components/Ingredients/TextAreaItem/index.tsx
  client/src/components/Ingredients/TextAreaItem/useTextAreaItem.ts
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/useFormulaList.ts
  client/src/components/Meal/InputArea/index.tsx
  client/src/components/Meal/InputContents/index.tsx
  client/src/components/Meal/Main/Content.tsx
  client/src/components/Meal/Main/useContent.ts
  client/src/components/Meal/OutputArea/index.tsx
  client/src/components/Meal/OutputContents/index.tsx
  client/src/components/Meal/SaveButtons/index.tsx
  client/src/components/Meal/Tab/MenuItem.tsx
  client/src/components/Meal/Tab/index.tsx
  client/src/components/Meal/Tab/useMenuItem.ts
  client/src/components/Meal/Tab/useTab.ts
  client/src/components/Set/Header/index.tsx
  client/src/pages/MainPage.tsx
Labels: 🖼️ frontend, 🧥 refactor
