Repository boostcamp-2020/Project15-C-Client-Based-Formula-Editor, pull requests merged in 2020-12, with the labels that each got.

#53 #13 - 드롭다운 수식 리스트의 스타일 수정
  client/public/content.css
  client/src/components/Ingredients/DropDownItem/index.tsx
  client/src/components/Ingredients/DropDownItem/style.ts
  client/src/components/Ingredients/FormulaItem/index.tsx
  client/src/components/Ingredients/FormulaItem/style.ts
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/FormulaList/useFormulaList.ts
  client/src/components/Set/Header/style.ts
  client/src/lib/constants/latex-header.ts
Labels: ⚒️ feature, 🖼️ frontend, 🧥 refactor

#55 #48, #49 서식 크기 및 정렬 변경
  client/src/components/Ingredients/FontSizeList/index.tsx
  client/src/components/Ingredients/FontSizeList/style.ts
  client/src/components/Ingredients/FontSizeList/useFontSizeList.ts
  client/src/components/Meal/FormatButtons/index.tsx
  client/src/components/Meal/FormatButtons/style.ts
  client/src/components/Meal/FormatButtons/useFormatButtons.ts
  client/src/components/Meal/OutputContents/index.tsx
  client/src/components/Meal/OutputFormula/index.tsx
  client/src/components/Meal/OutputFormula/style.ts
  client/src/components/Meal/TemplateButtons/index.tsx
  client/src/components/Meal/TemplateButtons/useTemplateButtons.ts
  client/src/contexts/latex/actions.ts
  client/src/contexts/latex/reducer.ts
  client/src/contexts/latex/types.ts
  client/src/hooks/useToggle.ts
  client/src/lib/constants/constants.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: ⚒️ feature, ✔️ must, 🖼️ frontend, 🧥 refactor

#56 #47 - 글씨 색상 변경 구현
  client/package-lock.json
  client/package.json
  client/src/components/Ingredients/FontColor/index.tsx
  client/src/components/Meal/FormatButtons/index.tsx
  client/src/components/Meal/OutputFormula/index.tsx
  client/src/components/Meal/OutputFormula/style.ts
  client/src/contexts/latex/actions.ts
  client/src/contexts/latex/reducer.ts
  client/src/contexts/latex/types.ts
Labels: ⚒️ feature, 🖼️ frontend

#57 #48,#49 Merge 해결 및 폴더명 변경
  client/src/components/Ingredients/FontColorMenu/index.tsx
  client/src/components/Ingredients/FontSizeMenu/index.tsx
  client/src/components/Ingredients/FontSizeMenu/style.ts
  client/src/components/Ingredients/FontSizeMenu/useFontSizeList.ts
  client/src/components/Meal/FormatButtons/index.tsx
  client/src/components/Meal/FormatButtons/useFormatButtons.ts
  client/src/contexts/latex/types.ts
  client/src/hooks/useToggle.ts
Labels: 🧥 refactor

#60 #15 - 서버쪽 초기 설정 및 symbolheader 관련 수식 추가
  client/src/components/Meal/FormulaList/useFormulaList.ts
  client/src/lib/constants/latex-header.ts
  server/.env.sample
  server/.eslintrc.js
  server/.prettierrc
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/router/index.ts
  server/tsconfig.json
Labels: ⚒️ feature, 📡 backend, 🖼️ frontend, 🧥 refactor

#61 Redux latex/EDIT 액션 리팩토링
  client/src/components/Ingredients/FontColorMenu/index.tsx
  client/src/components/Ingredients/FontSizeMenu/useFontSizeList.ts
  client/src/components/Ingredients/PageTabItem/index.tsx
  client/src/components/Ingredients/TextAreaItem/useTextAreaItem.ts
  client/src/components/Meal/FormatButtons/useFormatButtons.ts
  client/src/components/Meal/OutputFormula/useOutputFormula.ts
  client/src/contexts/latex/actions.ts
  client/src/contexts/latex/reducer.ts
  client/src/contexts/latex/types.ts
Labels: 🖼️ frontend, 🧥 refactor

#63 # 40 - 수식사전 수식 추가 및 symbolHeader 수식 검사
  client/src/lib/constants/constants.ts
  client/src/lib/constants/formula-dictionary.ts
  client/src/lib/constants/latex-header.ts
Labels: ⚒️ feature, 🖼️ frontend

#64 서식 바깥 누를 때 닫히게 설정
  client/public/content.css
  client/src/App.tsx
  client/src/components/Ingredients/FontColorMenu/index.tsx
  client/src/components/Ingredients/FontColorMenu/style.ts
  client/src/components/Ingredients/FontColorMenu/useFontColorMenu.ts
  client/src/components/Ingredients/FontSizeMenu/index.tsx
  client/src/components/Ingredients/FontSizeMenu/style.ts
  client/src/components/Ingredients/FontSizeMenu/useFontSizeList.ts
  client/src/components/Ingredients/FontSizeMenu/useFontSizeMenu.ts
  client/src/components/Meal/FormatButtons/index.tsx
  client/src/components/Meal/FormatButtons/style.ts
  client/src/components/Meal/FormatButtons/useFormatButtons.ts
  client/src/hooks/useToggle.ts
  client/src/lib/utils/util.ts
  client/src/pages/MainPage.tsx
Labels: ✔️ must, 🖼️ frontend

#66 #46 - 라텍스 문법 수정 및 최신화
  client/package-lock.json
  client/package.json
  client/src/components/Ingredients/FontColorMenu/style.ts
  client/src/lib/constants/latex-header.ts
Labels: 🖼️ frontend, 🧥 refactor

#65 #41 - 백엔드 favorite api 관련 로직 틀 구현
  server/.eslintrc.js
  server/src/controllers/favorite-controller.ts
  server/src/router/favorite-router.ts
  server/src/router/index.ts
  server/src/service/favorite-service.ts
Labels: 📚 api, 📡 backend

#68 #41 typeORM setting
  server/ormconfig.js
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/favorite-controller.ts
  server/src/entity/Favorite.ts
  server/src/entity/User.ts
  server/src/repository/favorite-repository.ts
  server/src/repository/user-repository.ts
  server/src/router/favorite-router.ts
  server/src/service/favorite-service.ts
  server/tsconfig.json
Labels: ✔️ must, 📚 api, 📡 backend

#70 #44 - 즐겨찾기 CSS 및 디자인 구현
  client/src/components/Ingredients/PageTabItem/useTextAreaItem.ts
  client/src/components/Ingredients/TableItem/index.tsx
  client/src/components/Ingredients/TableItem/style.ts
  client/src/components/Ingredients/TableItem/useTableItem.ts
  client/src/components/Meal/FavoriteTab/index.tsx
  client/src/components/Meal/FavoriteTab/style.ts
  client/src/components/Meal/InputContents/index.tsx
  client/src/components/Set/Input/style.ts
  client/src/components/Set/Output/style.ts
  client/src/lib/apis/api.ts
  client/src/lib/apis/common.ts
  client/src/lib/apis/favorite.ts
Labels: ⚒️ feature, 🖼️ frontend

#73 #69 백엔드 API 구현
  server/package.json
  server/src/app.ts
  server/src/controllers/favorite-controller.ts
  server/src/repository/favorite-repository.ts
  server/src/repository/user-repository.ts
  server/src/router/favorite-router.ts
  server/src/service/favorite-service.ts
  server/src/utils/constant.ts
  server/src/utils/validator.ts
  server/tsconfig.json
Labels: ⚒️ feature, ✔️ must, 📚 api, 📡 backend

#74 #43 수식 사전 리팩토링 진행
  client/FETCH_HEAD
  client/client@1.0.0
  client/src/components/Ingredients/DictionaryItem/index.tsx
  client/src/components/Ingredients/DictionaryItem/style.ts
  client/src/components/Ingredients/DictionaryMenuItem/index.tsx
  client/src/components/Ingredients/DictionaryMenuItem/style.ts
  client/src/components/Meal/DictionaryHeader/index.tsx
  client/src/components/Meal/DictionaryHeader/style.ts
  client/src/components/Meal/DictionaryItemList/index.tsx
  client/src/components/Meal/DictionaryItemList/style.ts
  client/src/components/Meal/DictionaryTab/index.tsx
  client/src/components/Meal/DictionaryTab/style.ts
  client/src/components/Meal/DictionaryTab/useDictionaryTab.ts
  client/src/components/Meal/InputContents/index.tsx
  client/src/components/Set/Input/index.tsx
  client/src/hooks/useInput.ts
  client/src/hooks/useSelect.ts
  client/src/lib/constants/latex-dictionary.ts
  client/tsconfig.json
  client/webpack-dev-server
Labels: ✔️ must, 🖼️ frontend, 🧥 refactor

#75 #43 Latex Dictionary 완성
  client/FETCH_HEAD
  client/client@1.0.0
  client/src/lib/constants/latex-dictionary.ts
Labels: ✔️could, 🖼️ frontend, 🧥 refactor

#78 #77 검색시 렉걸리는 현상 완화 및 검색과 셀렉트 서로 초기화
  client/src/components/Meal/DictionaryItemList/index.tsx
  client/src/components/Meal/DictionaryTab/index.tsx
  client/src/components/Meal/DictionaryTab/useDictionaryTab.ts
  client/src/lib/constants/constants.ts
  client/src/lib/constants/latex-dictionary.ts
Labels: ✔️ must, 🖼️ frontend, 🧥 refactor

#79 #42 Naver Login local 환경 구현
  client/public/index.html
  client/src/pages/MainPage.tsx
  client/src/pages/testComponent.tsx
Labels: ✔️could, 📚 api, 📡 backend

#82 백엔드 isValidateType, 프론트 timer type 변경
  client/src/components/Meal/DictionaryTab/useDictionaryTab.ts
  server/src/utils/validator.ts
Labels: 📡 backend, 🖼️ frontend

#84 #83 환경변수에 따라 개발 환경 or 크롬 익스텐션으로 작동하게 변경
  client/package.json
  client/src/App.tsx
  client/src/components/Ingredients/DropDownItem/style.ts
  client/src/components/Ingredients/FormulaItem/style.ts
  client/src/index.tsx
  client/src/lib/utils/util.ts
  client/webpack-dev-server
  client/webpack.config.js
Labels: ✔️ must, 🐞 bugfix, 🖼️ frontend

#86 setTimeout type 수정
  client/src/components/Meal/DictionaryTab/useDictionaryTab.ts
Labels: 🐞 bugfix

#88 #87 이미지로 저장 및 텍스트로 저장 기능 구현
  client/package-lock.json
  client/package.json
  client/public/content.css
  client/src/components/Ingredients/DictionaryItem/index.tsx
  client/src/components/Meal/OutputContents/index.tsx
  client/src/components/Meal/OutputFormula/index.tsx
  client/src/components/Meal/OutputFormula/style.ts
  client/src/components/Meal/OutputFormula/useOutputFormula.ts
  client/src/components/Set/SaveButtons/index.tsx
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/contexts/latex/actions.ts
  client/src/contexts/latex/reducer.ts
  client/src/contexts/latex/types.ts
  client/tsconfig.json
Labels: ⚒️ feature, ✔️ must, 🖼️ frontend

#89 #42 - 네이버 아이디로 로그인 구현
  client/public/background.js
  client/public/manifest.json
  server/package-lock.json
  server/package.json
  server/src/controllers/auth-controller.ts
  server/src/controllers/favorite-controller.ts
  server/src/router/auth-router.ts
  server/src/router/index.ts
  server/src/service/auth-service.ts
Labels: ⚒️ feature, 📚 api, 📡 backend, 🖼️ frontend

#90 #42 기존의 코드에 맞게 로그인 버튼 수정
  client/src/components/Set/SaveButtons/index.tsx
  client/src/components/Set/SaveButtons/useSaveButtons.ts
Labels: 🧥 refactor

#92 login api 관련 로직 구현 및 chrome storage 로직 구현
  client/public/background.js
  client/public/manifest.json
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/lib/utils/token.ts
  server/package-lock.json
  server/package.json
  server/src/controllers/auth-controller.ts
  server/src/repository/user-repository.ts
  server/src/service/auth-service.ts
  server/src/service/user-service.ts
Labels: ⚒️ feature, 📚 api, 📡 backend, 🖼️ frontend

#93 #87 - Latex 화면적용 기능 구현
  client/package-lock.json
  client/package.json
  client/public/content.css
  client/src/components/Set/SaveButtons/index.tsx
  client/src/components/Set/SaveButtons/style.ts
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/contexts/latex/reducer.ts
  client/src/lib/constants/latex-header.ts
Labels: ⚒️ feature, 🖼️ frontend

#94 #50, #51 - 즐겨찾기 UI 구현
  .gitignore
  client/public/background.js
  client/public/manifest.json
  client/src/components/Meal/FavoriteModal/index.tsx
  client/src/components/Meal/FavoriteModal/style.ts
  client/src/components/Meal/FavoriteModal/useFavoriteModal.ts
  client/src/components/Meal/OutputFormula/index.tsx
  client/src/components/Meal/OutputFormula/style.ts
  client/src/components/Meal/OutputFormula/useOutputFormula.ts
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/contexts/index.ts
  client/src/contexts/modal/actions.ts
  client/src/contexts/modal/index.ts
  client/src/contexts/modal/reducer.ts
  client/src/contexts/modal/types.ts
  client/src/pages/MainPage.tsx
  server/.env.sample
  server/src/repository/user-repository.ts
  server/src/service/auth-service.ts
  server/src/service/user-service.ts
Labels: ⚒️ feature, 📡 backend, 🖼️ frontend

#95 #44 User Redux 구현
  client/package-lock.json
  client/package.json
  client/public/image/login.png
  client/public/image/logout.png
  client/src/components/Ingredients/TableItem/index.tsx
  client/src/components/Meal/FavoriteTab/index.tsx
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/FormulaList/useFormulaList.ts
  client/src/components/Set/Header/index.tsx
  client/src/components/Set/SaveButtons/index.tsx
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/contexts/index.ts
  client/src/contexts/latex/actions.ts
  client/src/contexts/latex/types.ts
  client/src/contexts/user/actions.ts
  client/src/contexts/user/index.ts
  client/src/contexts/user/reducer.ts
  client/src/contexts/user/thunk.ts
  client/src/contexts/user/types.ts
  client/src/index.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/testComponent.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: ⚒️ feature, ✔️ must, 📚 api, 🖼️ frontend

#96 #44 User Redux Refactoring
  client/package.json
  client/src/components/Ingredients/TableItem/index.tsx
  client/src/components/Meal/FavoriteTab/index.tsx
  client/src/contexts/latex/actions.ts
  client/src/contexts/latex/reducer.ts
  client/src/contexts/latex/types.ts
  client/src/contexts/user/actions.ts
  client/src/contexts/user/reducer.ts
  client/src/contexts/user/thunk.ts
  client/src/contexts/user/types.ts
  client/src/lib/apis/favorite.ts
Labels: 🖼️ frontend, 🧥 refactor

#97 #44 #45 #50 #51 즐겨찾기 버그 수정 및 기능 구현
  client/public/background.js
  client/src/components/Ingredients/FontSizeMenu/useFontSizeMenu.ts
  client/src/components/Ingredients/TableItem/index.tsx
  client/src/components/Meal/FavoriteModal/index.tsx
  client/src/components/Meal/FavoriteModal/useFavoriteModal.ts
  client/src/components/Meal/FavoriteTab/index.tsx
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/FormulaList/useFormulaList.ts
  client/src/components/Meal/OutputFormula/index.tsx
  client/src/components/Meal/OutputFormula/style.ts
  client/src/contexts/user/actions.ts
  client/src/contexts/user/reducer.ts
  client/src/contexts/user/types.ts
  client/src/lib/apis/common.ts
  client/src/lib/apis/favorite.ts
  client/src/lib/utils/token.ts
  client/src/pages/MainPage.tsx
  client/webpack.config.js
  server/src/controllers/auth-controller.ts
  server/src/controllers/favorite-controller.ts
  server/src/repository/user-repository.ts
  server/src/router/index.ts
  server/src/service/auth-service.ts
  server/src/utils/constant.ts
Labels: ⚒️ feature, ✔️ must, 🐞 bugfix, 📡 backend, 🖼️ frontend

#106 pug 파일 간단한 css 수정
  server/src/views/index.pug
  server/src/views/layout.pug
Labels: 📡 backend

#107 #98 - QRCODE 기능 구현
  client/.env.sample
  client/package-lock.json
  client/package.json
  client/src/components/Ingredients/ModalItem/index.tsx
  client/src/components/Ingredients/ModalItem/style.ts
  client/src/components/Meal/InputContents/index.tsx
  client/src/components/Set/SaveButtons/index.tsx
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/contexts/latex/reducer.ts
  client/src/hooks/useModal.tsx
  client/src/index.tsx
  client/src/lib/apis/common.ts
  client/webpack.config.js
  server/src/views/index.pug
Labels: ⚒️ feature, 📚 api, 📡 backend, 🖼️ frontend

#108 #67 - 헤더 버튼 호버에서 클릭으로 수정
  client/package-lock.json
  client/src/components/Ingredients/DropDownItem/index.tsx
  client/src/components/Ingredients/DropDownItem/style.ts
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/FormulaList/useFormulaList.ts
Labels: 🖼️ frontend, 🧥 refactor

#109 #58 로딩화면 구현, 자동완성 임시 구현
  client/public/image/chef.gif
  client/public/image/formula.gif
  client/public/image/giphy.gif
  client/public/image/loading.gif
  client/public/image/login2.png
  client/public/image/login3.png
  client/public/image/logo.png
  client/public/image/logout2.png
  client/src/App.tsx
  client/src/components/Ingredients/AlertItem/index.tsx
  client/src/components/Ingredients/ButtonItem/index.tsx
  client/src/components/Meal/DictionaryItemList/index.tsx
  client/src/components/Meal/FavoriteModal/index.tsx
  client/src/components/Meal/FavoriteModal/style.ts
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/InputContents/index.tsx
  client/src/components/Set/Input/index.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/TestComponet.tsx
  client/webpack.config.js
Labels: ✔️ must, 🖼️ frontend, 🧥 refactor

#111 #77 - logo 및 header css 수정
  client/src/components/Meal/FormatButtons/style.ts
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Set/SaveButtons/index.tsx
  client/src/components/Set/SaveButtons/style.ts
Labels: ⚒️ feature, 🖼️ frontend

#112 Modal 관련 리팩토링
  client/src/components/Ingredients/QrCode/index.tsx
  client/src/components/Ingredients/QrCode/style.ts
  client/src/components/Meal/FavoriteModal/index.tsx
  client/src/components/Meal/FavoriteModal/useFavoriteModal.ts
  client/src/components/Meal/OutputFormula/index.tsx
  client/src/components/Meal/OutputFormula/useOutputFormula.ts
  client/src/components/Set/SaveButtons/index.tsx
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/contexts/index.ts
  client/src/contexts/modal/actions.ts
  client/src/contexts/modal/index.ts
  client/src/contexts/modal/reducer.ts
  client/src/contexts/modal/types.ts
  client/src/hooks/useModal.tsx
  client/src/pages/MainPage.tsx
Labels: 🖼️ frontend, 🧥 refactor

#119 #115 - 라텍스 문법 수정 및 디자인 수정
  client/package-lock.json
  client/package.json
  client/public/content.css
  client/src/components/Meal/OutputFormula/style.ts
  client/src/contexts/latex/reducer.ts
  client/src/lib/constants/latex-header.ts
Labels: 🖼️ frontend, 🧥 refactor

#117 #100 - 크롬 검수에 맞게 코드 수정
  client/public/background.js
  client/public/icon.png
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/OutputFormula/index.tsx
  client/src/components/Set/SaveButtons/index.tsx
  client/src/index.tsx
  client/src/lib/apis/common.ts
  client/src/lib/utils/token.ts
  client/src/pages/TestComponet.tsx
Labels: 🧥 refactor

#120 #116 Resize 구현
  client/public/content.css
  client/public/image/login4.png
  client/src/components/Ingredients/TextAreaItem/index.tsx
  client/src/components/Ingredients/TextAreaItem/style.ts
  client/src/components/Meal/InputContents/index.tsx
  client/src/components/Meal/MenuBar/index.tsx
  client/src/components/Meal/MenuBar/style.ts
  client/src/components/Meal/OutputContents/index.tsx
  client/src/components/Meal/OutputFormula/index.tsx
  client/src/components/Meal/OutputFormula/style.ts
  client/src/components/Set/Output/index.tsx
  client/src/components/Set/ResizeHeader/index.tsx
  client/src/components/Set/ResizeHeader/style.ts
  client/src/pages/MainPage.tsx
Labels: ⚒️ feature, ✔️ must, 🖼️ frontend

#118 QrCode axios로 변경, useThrottle로 분리 및 헤더 부분 구조 변경 및 스타일 수정
  client/src/components/Meal/DictionaryTab/useDictionaryTab.ts
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Set/Header/index.tsx
  client/src/components/Set/Header/style.ts
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/hooks/useThrottle.ts
Labels: 🖼️ frontend, 🧥 refactor

#121 formulaList width 수정 및 자동완성 기능 구현
  client/src/components/Ingredients/RecommendItem/index.tsx
  client/src/components/Ingredients/TextAreaItem/index.tsx
  client/src/components/Ingredients/TextAreaItem/style.ts
  client/src/components/Ingredients/TextAreaItem/useTextAreaItem.ts
  client/src/components/Meal/FormulaList/style.ts
  client/src/lib/constants/latex-header.ts
Labels: ⚒️ feature, ✔️should, 🖼️ frontend

#122 # 102 @검색 부분 스타일 및 기능 최적화, 그 외 header 등 style 수정
  client/src/components/Ingredients/RecommendItem/index.tsx
  client/src/components/Ingredients/RecommendItem/style.ts
  client/src/components/Ingredients/TextAreaItem/index.tsx
  client/src/components/Ingredients/TextAreaItem/style.ts
  client/src/components/Ingredients/TextAreaItem/useTextAreaItem.ts
  client/src/components/Meal/DictionaryTab/useDictionaryTab.ts
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/InputContents/index.tsx
  client/src/components/Meal/MenuBar/index.tsx
  client/src/components/Set/Header/style.ts
  client/src/hooks/useDebounce.ts
  client/src/hooks/useThrottle.ts
Labels: ✔️should, 🖼️ frontend, 🧥 refactor

#124 # 115 - 행렬 입력받는 수식 기능 추가
  client/src/components/Ingredients/FormulaItem/index.tsx
  client/src/components/Ingredients/FormulaItem/style.ts
  client/src/components/Ingredients/FormulaItem/useFormulaItem.ts
  client/src/lib/constants/latex-header.ts
Labels: ⚒️ feature, 🖼️ frontend

#125 #114 즐겨찾기 수정 및 폰트 적용
  client/public/content.css
  client/public/root.css
  client/src/App.tsx
  client/src/components/Ingredients/AlertItem/index.tsx
  client/src/components/Ingredients/IconMessage/index.tsx
  client/src/components/Ingredients/IconMessage/style.ts
  client/src/components/Meal/FavoriteModal/style.ts
  client/src/components/Meal/MenuBar/index.tsx
  client/src/components/Meal/MenuBar/style.ts
  client/src/components/Meal/OutputFormula/index.tsx
  client/src/components/Meal/OutputFormula/style.ts
  client/src/components/Meal/OutputFormula/useOutputFormula.ts
  client/src/components/Meal/OutputFormulaBox/index.tsx
  client/src/components/Meal/OutputFormulaBox/style.ts
  client/src/components/Meal/OutputFormulaBox/useOutputFormulaBox.ts
  client/src/components/Set/Header/index.tsx
  client/src/components/Set/Header/style.ts
  client/src/components/Set/ResizeHeader/index.tsx
  client/src/components/Set/ResizeHeader/style.ts
  client/src/hooks/useModal.tsx
  client/src/pages/MainPage.tsx
Labels: 🐞 bugfix, 🖼️ frontend

#126 auto login error 해결
  client/public/background.js
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/lib/utils/token.ts
Labels: 🐞 bugfix

#127 auto login server logic 수정
  server/src/controllers/auth-controller.ts
Labels: 🐞 bugfix

#128 #42 Login 성공, 실패시 메시지 추가
  client/public/background.js
  client/src/components/Ingredients/MessageItem/index.tsx
  client/src/components/Ingredients/MessageItem/style.ts
  client/src/components/Set/SaveButtons/index.tsx
  client/src/components/Set/SaveButtons/style.ts
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/lib/constants/constants.ts
Labels: ⚒️ feature, ✔️should, 🖼️ frontend

#129 #116 전체 오류 및 버그, 디자인 수정
  client/src/components/Ingredients/RecommendItem/index.tsx
  client/src/components/Ingredients/RecommendItem/style.ts
  client/src/components/Ingredients/TextAreaItem/index.tsx
  client/src/components/Ingredients/TextAreaItem/style.ts
  client/src/components/Ingredients/TextAreaItem/useTextAreaItem.ts
  client/src/components/Meal/FavoriteModal/style.ts
  client/src/components/Meal/FavoriteTab/style.ts
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/OutputFormula/style.ts
  client/src/components/Meal/OutputFormulaBox/index.tsx
  client/src/components/Meal/OutputFormulaBox/style.ts
  client/src/components/Set/Header/style.ts
  client/src/hooks/useModal.tsx
  client/src/lib/utils/token.ts
Labels: 🐞 bugfix, 🖼️ frontend, 🧥 refactor

#131 #103 - 계산기 탭 구현
  client/src/components/Meal/CalculatorTab/index.tsx
  client/src/components/Meal/CalculatorTab/style.ts
  client/src/components/Meal/CalculatorTab/useCalculatorTab.ts
  client/src/components/Meal/InputContents/index.tsx
  client/src/lib/constants/calculator.ts
Labels: ⚒️ feature, 🖼️ frontend

#132 #103 - 계산기 탭의 불필요한 border 삭제
  client/src/components/Meal/CalculatorTab/style.ts
Labels: 🧥 refactor

#137 로그인 시, 즐겨찾기 목록 불러오기
  client/public/background.js
  client/src/components/Set/SaveButtons/useSaveButtons.ts
Labels: 🐞 bugfix

#139 user 컬럼 수정
  server/src/entity/User.ts
  server/src/repository/user-repository.ts
  server/src/service/auth-service.ts
  server/src/service/user-service.ts
Labels: 📚 api, 📡 backend

#141 #103 - 근호 버튼 기능 동작하도록 수정 및 변수명 수정
  client/src/lib/constants/calculator.ts
Labels: 🧥 refactor

#140 #133, 136 - 헤더 QR코드 제거 및 부가설명추가 + 계산기 CSS 수정
  client/package-lock.json
  client/package.json
  client/public/content.css
  client/src/components/Ingredients/IconMessage/index.tsx
  client/src/components/Meal/CalculatorTab/index.tsx
  client/src/components/Meal/CalculatorTab/style.ts
  client/src/components/Meal/CalculatorTab/useCalculatorTab.ts
  client/src/components/Meal/MenuBar/index.tsx
  client/src/components/Meal/MenuBarInput/style.ts
  client/src/components/Meal/MenuBarOutput/style.ts
  client/src/components/Set/Input/style.ts
  client/src/lib/constants/calculator.ts
  client/src/lib/constants/latex-dictionary.ts
  client/src/lib/constants/latex-header.ts
Labels: 🖼️ frontend, 🧥 refactor

#143 화면 줄였을 때 아이콘 수정 및 전체적인 버튼 색 수정
  client/src/components/Meal/MenuBar/style.ts
  client/src/components/Meal/MenuBarInput/index.tsx
  client/src/components/Meal/MenuBarInput/style.ts
  client/src/components/Meal/MenuBarOutput/index.tsx
  client/src/components/Meal/MenuBarOutput/style.ts
  client/src/components/Meal/PageTab/style.ts
  client/src/components/Set/Header/style.ts
  client/src/lib/constants/constants.ts
Labels: 🧥 refactor

#142 #58 메인과 즐겨찾기 로딩 구현
  client/src/components/Ingredients/Loading/index.tsx
  client/src/components/Ingredients/Loading/style.ts
  client/src/components/Meal/FavoriteTab/index.tsx
  client/src/components/Meal/FavoriteTab/style.ts
  client/src/pages/MainPage.tsx
  client/src/pages/TestComponet.tsx
Labels: ⚒️ feature, ✔️should, 🖼️ frontend

#144 배포 전 오류 수정
  client/package-lock.json
  client/src/components/Ingredients/TableItem/index.tsx
  client/src/components/Ingredients/TableItem/style.ts
  client/src/components/Meal/CalculatorTab/useCalculatorTab.ts
  client/src/components/Meal/FavoriteTab/index.tsx
  client/src/components/Meal/MenuBar/index.tsx
  client/src/components/Set/SaveButtons/index.tsx
  client/src/components/Set/SaveButtons/style.ts
  client/src/lib/constants/formula-dictionary.ts
  client/src/lib/constants/latex-dictionary.ts
Labels: 🐞 bugfix

#145 #103 - 수식이 아닌 값이 적용되도록 버그 수정
  client/src/components/Meal/CalculatorTab/useCalculatorTab.ts
Labels: 🐞 bugfix

#146 #103 - 수식이 문자열로 저장되도록 수정
  client/src/components/Meal/CalculatorTab/useCalculatorTab.ts
Labels: 🐞 bugfix

#147 #99 백엔드 이미지 보여줄 때 마크업 및 CSS 추가
  server/public/icon.png
  server/src/app.ts
  server/src/views/index.pug
  server/src/views/layout.pug
Labels: 📡 backend

#150 #149 useSaveButtons 리팩토링 작업 수행
  client/package-lock.json
  client/package.json
  client/src/__tests__/ButtomItem.test.tsx
  client/src/__tests__/FontColorMenu.test.tsx
  client/src/__tests__/FontSizeMenu.test.tsx
  client/src/__tests__/IconMessage.test.tsx
  client/src/__tests__/Loading.test.tsx
  client/src/__tests__/MessageItem.test.tsx
  client/src/__tests__/PageItem.test.tsx
  client/src/__tests__/test.ts
  client/src/components/Ingredients/FontColorMenu/index.tsx
  client/src/components/Ingredients/FontColorMenu/style.ts
  client/src/components/Ingredients/FontColorMenu/useFontColorMenu.ts
  client/src/components/Ingredients/FontSizeMenu/index.tsx
  client/src/components/Ingredients/FormulaItem/index.tsx
  client/src/components/Ingredients/IconMessage/index.tsx
  client/src/components/Ingredients/ModalItem/index.tsx
  client/src/components/Ingredients/ModalItem/style.ts
  client/src/components/Ingredients/PageTabItem/usePageTabItem.ts
  client/src/components/Ingredients/PageTabItem/useTextAreaItem.ts
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Set/SaveButtons/index.tsx
  client/src/components/Set/SaveButtons/useSaveButtons.ts
  client/src/lib/constants/constants.ts
  client/src/lib/utils/test-util.tsx
  client/src/setUpTest.ts
Labels: 🐞 bugfix

#155 #149 - 헤더 부분 리팩토링 수행
  client/src/components/Ingredients/DropDownItem/index.tsx
  client/src/components/Ingredients/DropDownItem/style.ts
  client/src/components/Ingredients/FormulaItem/index.tsx
  client/src/components/Ingredients/FormulaItem/style.ts
  client/src/components/Ingredients/FormulaItem/useFormulaItem.ts
  client/src/components/Meal/FormulaList/index.tsx
  client/src/components/Meal/FormulaList/style.ts
  client/src/components/Meal/FormulaList/useFormulaList.ts
  client/src/components/Meal/MenuBar/index.tsx
  client/src/components/Set/Header/index.tsx
  client/src/lib/constants/constants.ts
Labels: 🧥 refactor
